### ISSUE TITLE
OAuth 2 Server - Dynamic client registration

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#109]
As per http://tools.ietf.org/html/draft-ietf-oauth-dyn-reg-05

Worth investigating how mature this protocol is before implementing. Will yield 1-2 self sustained (no use of grant types) additional endpoints.

**Comment by JonathanHuot** [comment]
The protocol is now finalized, and worth to be implemented in oauthlib. See the implementation discussion here https://github.com/oauthlib/oauthlib/issues/649
