### ISSUE TITLE
Keeping the source tidy, tested and documented

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#168]
While it is most fun to dig in and develop new features it is equally, if not more, important to keep the code clean, the tests unforgiving and the documentation clear. 

If you want to earn eternal fame and glory any help looking into
- Module descriptions, i.e. what the current file / package does
- Escalating file size, a file spanning hundreds of lines should likely be broken apart into several sub modules.
- Method documentation should include parameter descriptions and a short overview of what its purpose is. Interactive style examples are great to have as well.
- Documentation is rendered with Sphinx and can utilize a range of nice mark up features which can be used to make it easier to digest, i.e. code block highlighting and cross referencing.
- Any PEP8 violations.
- Lack of code coverage
- Lack of edge case tests exercising input sizes and encodings
- Messy imports. Should preferably be uniform and ordered alphabetically.
- Widespead py 2/3 compatability clauses that should be moved into a new oauthlib.compat
- And anything else you can think of to improve code and docs health

will be greatly appreciated =)

**Comment by duaneking** [comment]
It may be best if a "contributors guide" was added so that these rules are explicitly spelled out in the code so there is no lack of clarity.

For example, its common to run a python linter tool such as flake8; Maybe that should be the official standard for the project?
