### ISSUE TITLE
Do you have any examples on how to create provider that supports resource owner password credentials?

### ISSUE THREAD

**Issue by didip** [oauthlib/oauthlib#174]
I see that the library supports it:

https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py

**Comment by rhodesy** [comment]
Apologies for kicking up an old thread, but I've got myself into a bit of a kerfuffle. 

I've selected the Resource Owner Password Credentials grant for my website API (users log into my own website via a log in form - once signed in, they go to the restricted area which makes use of my own API). 

I've started implementing my own RequestValidator, using methods required for the Resource Owner Password Credentials grant; however, I'm not too sure what authenticate_client is used for in this instance?
