### ISSUE TITLE
"code token" aka "token code" Multiple-Valued Response Type

### ISSUE THREAD

**Issue by masci** [oauthlib/oauthlib#221]
Some OAuth2 providers like Facebook support a response type which acts both as _Authorization code_ and _Implicit grant_[0] at the same time for a single Application. RFC 6749 permits the registration of new token types[1] and "code token" seems to be registered in this document[2].

I'm not sure whether this whole thing is strictly compliant to the standard or not, so I was wondering if there is any plan to add support for this token type to oauthlib.

[0] http://developers.facebook.com/docs/facebook-login/login-flow-for-web-no-jssdk/
[1] http://tools.ietf.org/html/rfc6749#section-8.4
[2] http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations

**Comment by JonathanHuot** [comment]
OpenID Connect is part of the 3.x.x release
