### ISSUE TITLE
Enable relaxation of oauthlib.common.urldecode via Client interface

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#228]
Often urldecode chokes on certain characters the provider considers safe enough not to urlencode. It would be nice to have an interface to tweak this without monkey patching. In the Client constructor possibly.

Also see https://github.com/requests/requests-oauthlib/issues/99

**Comment by JonathanHuot** [comment]
Close since the downstream's issue has been closed.
