### ISSUE TITLE
Post Redirect Get with Status 303 instead of 302

### ISSUE THREAD

**Issue by twhtanghk** [oauthlib/oauthlib#281]
In OAuth2, it is expected to redirect browser to "GET" Web Application URL with token by status code 302 after browser "POST" the authorized scope to Authenticate Server. However, Internet Explorer not completely following the POST-REDIRECT-GET with status code 302. Is it feasible to return status code 303 instead of 302 in this case?

**Comment by JonathanHuot** [comment]
If anyone is still interested, please reopen and propose a PR.
