### ISSUE TITLE
Features and API changes should be deprecated before being removed

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#287]
To make new releases less disruptive features going away or APIs being changed in backwards incompatible ways should have deprecation warnings added first. When these deprecation warnings have lived live in a release for X amount of time then the breaking change can be applied.

Should update the release process with these details.

**Comment by JonathanHuot** [comment]
Semantic versioning seems a reasonnable choice. IMHO deprecation warnings is a nightmare to manage.

Others ?

**Comment by JonathanHuot** [comment]
With the current resources of the project, I'm proposing to stick with semantic versioning only and drop the deprecation idea.
