### ISSUE TITLE
Code reviews - please help me out :)

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#294]
If you would like to help oauthlib by doing code reviews please ping this issue and I will ask you to review  pull requests I make in the future. 

Your help will be much appreciated!

**Comment by tilgovi** [comment]
Ping.

**Comment by josephtate** [comment]
Sign me up.

**Comment by shookees** [comment]
Ping

**Comment by JonathanHuot** [comment]
We do have a contribution section now https://oauthlib.readthedocs.io/en/latest/contributing.html
