### ISSUE TITLE
Additional information in failures

### ISSUE THREAD

**Issue by samskiter** [oauthlib/oauthlib#312]
Hi, we've implemented an e-mail confirmation system that prevents a user logging in till they've clicked a link we send them. To reject the user's login was pretty simple, just check in validate_user whether a confirmedEmail boolean is set for the user. However, to help our users, we'd like to be able to tell them why they can't login client side.

I can't seem to find an easy way of introducing this information into the JSON that is returned by the server. (I've been looking through grant types and errors, but struggling). What would be the least-resistance point to inject this behaviour, and would there be any scope for a future ability to do this? (Perhaps setting something on the request in validate_user that is picked up in errors.py ? )

Thanks,

Sam

**Comment by JonathanHuot** [comment]
You can create your own OAuth2Error by overriding the `error_description` to fit whatever message you need.
