### ISSUE TITLE
Custom Grant Type

### ISSUE THREAD

**Issue by BraisGabin** [oauthlib/oauthlib#390]
Hi, is there a way to implement a custom grant type? If there is not I can contribute with a PR.

**Comment by leonid-s-usov** [comment]
As I understand, there is: you should define your own subclass of the `GrantTypeBase` with your custom logic. 

Next, to use the grant type you would need to create your own `Server` class following pattern found in https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/endpoints/pre_configured.py

However, It seems that there could be a more elegant approach if the classes defined in `pre_configured.py` would allow for passing in as a parameter additional token and grant type handlers

**Comment by JonathanHuot** [comment]
Implementing a custom grant type is doable, however the documentation should have this kind of examples.
If you can find a real-world example, or improve the doc, feel free to submit a PR :-)
