### ISSUE TITLE
MobileApplicationClient and non-https token redirects

### ISSUE THREAD

**Issue by untitaker** [oauthlib/oauthlib#392]
I use `MobileApplicationClient` in a desktop application that doesn't rely on any other servers than the OAuth and resource ones. In order to avoid any token leakage, I instruct the server to redirect to an URI with a custom scheme, which is then catched by my application (which only can be done per-scheme). Something like the following redirect URI:

```
myapplication:access_token#access_token=...
```

Unfortunately, `MobileApplicationClient.parse_request_uri_response` doesn't think this URI is secure enough (since it's not HTTPS). But in fact it is more secure than having the OAuth server redirect to a third-party HTTPS server.

**Comment by untitaker** [comment]
The above example is only hypothetical, the actual usecase involves a command-line application which can't catch any URIs at all, while the server supports only one auth flow.

**Comment by JonathanHuot** [comment]
Feel free to open a PR if still wanted.
