### ISSUE TITLE
Designing OAuth2 client support

### ISSUE THREAD

**Issue by ib-lundgren** [oauthlib/oauthlib#44]
Thought I'd get some discussion going on how to best approach the versatility of OAuth2 client profiles and token types. While OAuth 2 is a fair bit simpler than OAuth1 I still think having several Client classes would be advantageous. Mainly because each client comes with its own set of "quirks" in the request/response flow.  Also, unlike OAuth1 extensibility plays a major role in OAuth2 and I think it would be easy to add extension client classes this way. For example the [Google Service Accounts grant model](https://developers.google.com/accounts/docs/OAuth2ServiceAccount). Furthermore, having several clients make it more explicit that there are differences between them, this is very important from a security point of view because although they may look similar they are built on vastly different security premises (im looking at you auth code and implicit grant). 

My idea for how these clients might look is based on thinly wrapping #18. The clients share enough functionality to work well of a base class with 3 polymorhpic methods. 

```
Client(object):
    # the base client, has the ability to add "bearer" and "mac" tokens

    def __init__(self, ....):
        # sets up token type and related values

    def add_token(self, uri, http_method=u'GET', body=None, headers=None):
        # attaches tokens either to uri, auth header or body in the case of
        # bearer tokens, and to auth header if mac token
        # this is a very basic operation for both token types

    def validate_token_params(self, ...):
        # param validation is the same for all client profiles but highly
        # recommended by the spec for security reasons

    def prepare_token_uri(self, ...):
        raise NotImplementedError(..)

    def parse_token_uri_response(self, response):
        # extracts and validates params from response
        # params are added to self 
        # abstract because it differs in implicit/auth code
        raise NotImplementedError(..) 

    def prepare_token_body(self, ...):
        raise NotImplementedError(..)

    def parse_token_body_response(self, response):
        # extracts and validates params from response
        # params are added to self   
        # not abstract since its the same for all profiles

ConfidentialClient(Client):
    # follows the authorization code grant model
    # overrides all abstract methods:
    # prepare_token_uri, parse_token_uri_response, prepare_token_body

PublicClient(Client):
    # follows the implicit code grant model
    # overrides prepare_token_uri & parse_token_uri_response

CredentialsClient(Client):
    # follows the client credentials grant model
    # overrides prepare_token_body

PasswordClient(Client):
    # follows the resource owner password credentials grant
    # overrides prepare_token_body
```

Any input on how to properly name the parse-and-populate methods would be awesome. Oh, and remember that the responses for OAuth2 are clearly defined and thus easily parsable =)

**Comment by JonathanHuot** [comment]
Closing since the majority of the ticket has been implemented.
