### ISSUE TITLE
Mac headers are calculated incorrectly for OAuth2

### ISSUE THREAD

**Issue by nderkach** [oauthlib/oauthlib#454]
I'm using the following example from the IETF specification: https://tools.ietf.org/html/draft-ietf-oauth-v2-http-mac-01#section-1.1

If you run [this code snippet](https://gist.github.com/nderkach/663532a8ffc83b02b022b9672ecdc0fd) you can see that there is a mismatch between expected and actual calculated mac. The snippet is taken from the library code with a slight modification to disable generation of nonce and ts. Any idea what's wrong here?

**UPD**: I don't see any issues with oauthlib implementation of draft 1, so could that be that the error is in the spec itself?

**Comment by kevin-brown** [comment]
Note that the version of the specification which you are looking at is not the most recent version. You're looking at the first draft, but they got up to draft 5: https://tools.ietf.org/html/draft-ietf-oauth-v2-http-mac-05

**Comment by JonathanHuot** [comment]
I close since the reporter concluded to a good implementation in oauthlib
