### ISSUE TITLE
Is there anyway to change the error response format

### ISSUE THREAD

**Issue by arunssjoshi** [oauthlib/oauthlib#460]
Thank you very much for the wonderful project. I have implemented in my app it working great. Is there any way to change the error response format? That is, I need to change

`"error_description": "Invalid credentials given.",`

to 
`"detail": "Invalid credentials given.",`

Is there anyway to change the format? I already asked this question in stackoverflow, But I haven't got any response from there.

**Comment by wiliamsouza** [comment]
What is the use case for this change?

**Comment by duaneking** [comment]
There is no current plan to allow this to be changed, as the RFC requires this field name and changing it would be a violation of the RFC per https://tools.ietf.org/html/rfc6749#section-4.1.2.1

**Comment by JonathanHuot** [comment]
Agree with @duaneking, the RFC expicitly mention `error_description`. 

@arunssjoshi, if you want to hack your project and customize the error fields there, feel free to do so, but be aware you will no longer be compliant with OAuth2.0 standards clients.

This ticket can be closed

**Comment by duaneking** [comment]
Closing Issue as it is not a defect per the RFC.
