### ISSUE TITLE
What happened to the documentation on Grant Types under OAuth2?

### ISSUE THREAD

**Issue by jontycg** [oauthlib/oauthlib#489]
It looks like all of the docs have been deleted? 

Example: https://oauthlib.readthedocs.io/en/latest/oauth2/grants/authcode.html

**Comment by duaneking** [comment]
Documentation would really be nice given the recent OIDC changes that have seemed to change the default behavior.

**Comment by dhrp** [comment]
Not sure why, but I did stumble across a different branch on RTD 'stable' where documentation has been retained. It's no longer in git master though.

https://oauthlib.readthedocs.io/en/stable/oauth2/grants/authcode.html

**Comment by JonathanHuot** [comment]
May be related to #516

**Comment by JonathanHuot** [comment]
It's now fixed since 2.0.7 release. Thanks for your report!
