### ISSUE TITLE
OAuth2.0 Token Introspection

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#497]
Hi guys,

I would like to know if someone already had a look on the [RFC 7662 "OAuth2.0 Token Introspection](https://tools.ietf.org/html/rfc7662)" ? 
That's a pretty simple extension which decipher a opaque token, and we're going to add this support to our OAuth2.0 authorization server.

Since the Introspection implementation is intrinsically linked to a RequestValidator implementation, I was wondering if this enhancement can be included into oauthlib project, and if anyone is interested by such features ?

Thank you for this excellent project.

**Comment by duaneking** [comment]
Would love to see this done.

**Comment by JonathanHuot** [comment]
We have completed a first implementation, where oauthlib support active:true/false and extra claims, plus an optional client authentication.

The fork/PR should be public soon.

**Comment by duaneking** [comment]
Thank You!

Does this include JWT token support?

**Comment by duaneking** [comment]
#50

**Comment by JonathanHuot** [comment]
Our implementation of Token Introspection involves a  JWT token support, but I believe it's the responsability of the oauthlib's RequestValidator implementor to do such statements.

Since it seems we cannot make assumptions of "how opaque" a token is, we delegated the entire introspection to the RequestValidator. And then, the oauthlib's RequestValidator do basic calls.

However, I'll be happy to have other views of our PR, soon available. Stay tuned,

**Comment by duaneking** [comment]
Looking forward to this! I was just looking at the code to see what would be required to get JWT working, so you may have beaten me to the punch.

**Comment by skion** [comment]
@JonathanHuot This sounds interesting, any luck with your PR?

**Comment by JonathanHuot** [comment]
@duaneking / @skion : feel free to review https://github.com/idan/oauthlib/pull/508 and comments! Thanks for your support.

**Comment by skion** [comment]
We merged this in #508, nice one @JonathanHuot!
