### ISSUE TITLE
Question: Is oauthlib being stricter than OIDC spec, disallowing use of prompt=none without 'id_token_hint'?

### ISSUE THREAD

**Issue by bjmc** [oauthlib/oauthlib#507]
According to the [OIDC spec](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest):

> id_token_hint
> OPTIONAL. ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client. If the End-User identified by the ID Token is logged in or is logged in by the request, then the Authorization Server returns a positive response; otherwise, it SHOULD return an error, such as login_required. When possible, an id_token_hint SHOULD be present when prompt=none is used and **an invalid_request error MAY be returned if it is not**; however, **the server SHOULD respond successfully when possible, even if it is not present**. The Authorization Server need not be listed as an audience of the ID Token when it is used as an id_token_hint value. 

(emphasis added)

Right now, the `oauthlib` library seems to be making that decision for the caller. The [OIDC validator raises an InvalidRequestError](https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/grant_types/openid_connect.py#L358) if `prompt=none` is sent without an accompanying `id_token_hint` parameter.

Is this what we want to be doing here? The spec leaves open the possibility for the server to identify the user by some other method (e.g. login cookie) even if `id_token_hint` is missing. In practice, I think that would be hard to do with oauthlib as currently written. Is the intention that the calling application could catch the `InvalidRequest` exception and handle it (as with the `LoginRequired` and `ConsentRequired` errors)? If so, how? The calling app would have to set some kind of value for `id_token_hint` to avoid hitting that check again.

**Comment by bjmc** [comment]
@skion I know it's been a while, but do you remember when you added this validation if you had something specific in mind for how a calling application could recover and proceed without an `id_token_hint`?

**Comment by skion** [comment]
Hi @bjmc, I didn't implement that logic, but did run into it while fixing something around `prompt=none`, which is probably the commit you saw. Just didn't have a need (nor time) to look into it in more detail.

So I agree its a bug, would you have any ideas on how to fix it?
