### ISSUE TITLE
OAuthLib upcoming release 3.0.0

### ISSUE THREAD

**Issue by wiliamsouza** [oauthlib/oauthlib#512]
**This is a backward incompatible release**

Release notes for OAuthLib 3 to be released in 2018-02-05.

Updates to changelog:

3.0.0 Add new release changelog
2.0.5 Was released in 2017-10-18 according https://pypi.python.org/pypi/oauthlib/2.0.5
2.0.5 Add an entry explaining the problem of releasing backward incompatible version.
2.0.6 This is revert release from  backward incompatible added in 2.0.5 notice.

CHANGELOG.rst
=

3.0.0 (2018-02-05)
------------------

**This is a backward incompatible release**

This release improves OpenID Connect supporting removing the need of using `grant_type=openid` in token endpoint and when defining a application credential the `authorization_grant_type` can be same already used (`authorization-code`) both for OpenID Connect and OAuth2.

Replaces the way to send a token from `Authorization: JWT eyJhbGciOiAiUlMyNTYifQ...` to `Authorization: Bearer eyJhbGciOiAiUlMyNTYifQ...`.

* OpenID connect improvements #484.
* Openid connect jwt #488

2.0.6 (2017-10-19)
------------------

This is revert release from  backward incompatible added in 2.0.5

* Fix cliend_id in web request body #505
* Added bottle-oauthlib #509
* Add support for HMAC-SHA256 (builds on PR#388) #498
* Check access token in self.token dict #500
* When deploying a release to PyPI, include the wheel distribution #496
* Include license file in the generated wheel package #494
* Refactor OAuth2Error
* Fix OAuth2Error.response_mode for #463.
* Documentation improvement.
* initialization of variable #487
* Pass through nonce in code flow #481

2.0.5 (2017-10-18)
------------------
**Do not use this version**

By mistake backward incompatible changes were released in this version the next reverts it.

**Comment by wiliamsouza** [comment]
@lepture @wwidnyana @evonove @masci @lundgren @lukasa As stated by OAuthLib release process [1] i'm letting you know before hand about this upcoming release!

[1] https://github.com/oauthlib/oauthlib/blob/master/docs/release_process.rst

**Comment by duaneking** [comment]
We really should support the official RFC for JWT before we claim to support OpenIDC, as we don't right now, and JWT is a hard requirement for it.

**Comment by wiliamsouza** [comment]
Can you please enumerate those RFCs?
We claim to support OpenID Connect Core 1.0 http://openid.net/specs/openid-connect-core-1_0.html and and we must let it explicit at the docs.

**Comment by duaneking** [comment]
http://openid.net/specs/openid-connect-core-1_0.html#JWTRequests

Explicitly stated as JWT's.

https://tools.ietf.org/html/rfc7519 - RFC for JWT's, meaning that #50 must be included before we can ay it supports the OIDC spec.

**Comment by jdelic** [comment]
I am somewhat looking forward to be able to support OpenID connect through `django-oauth-toolkit`. Is there a new ETA for the 3.0.0 release?  Perhaps someone in the know can quickly list what's blocking a release? That would be much appreciated.

**Comment by duaneking** [comment]
OpenID connect through `django-oauth-toolkit` was my original goal many months ago, but lack of JWT was the biggest issue.

**Comment by Diaoul** [comment]
I just noticed that my PR hasn't made it to release yet: https://github.com/oauthlib/oauthlib/pull/505

I suggest making a prerelease with the pending breaking changes merged so people can test it and/or use it at their own risk.

**Comment by duaneking** [comment]
I honestly feel like when it comes to these sort of releases with possibly backward breaking changes, we need to facilitate community input by also running unit tests for our big core upstream that they can provide.

Our customers for this are not a random non-technical user; So lets treat the devs that use the lib as the customers for it.

**Comment by Diaoul** [comment]
Can you bump version to a dev version in master branch? I don't see any downsides to that.

**Comment by JonathanHuot** [comment]
Master has its version bumped to 3.0.0-dev

**Comment by JonathanHuot** [comment]
Closed in favor of #619 . Please start another discussion there if you want to.
