### ISSUE TITLE
Push to PyPi fails

### ISSUE THREAD

**Issue by skion** [oauthlib/oauthlib#526]
See [Travis](https://travis-ci.org/oauthlib/oauthlib/jobs/354959897)...

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading oauthlib-2.0.5.tar.gz
100% 138k/138k [00:00<00:00, 418kB/s]  
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
oauthlib.egg-info/PKG-INFO already exists, no checkout
oauthlib.egg-info/SOURCES.txt already exists, no checkout
oauthlib.egg-info/dependency_links.txt already exists, no checkout
oauthlib.egg-info/requires.txt already exists, no checkout
oauthlib.egg-info/top_level.txt already exists, no checkout
oauthlib/__init__.pyc already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

Should we update the PyPi credentials for Travis?

**Comment by JonathanHuot** [comment]
Travis is using a private key for each project. So the previous secrets used for idan/oauthlib are no longer valid (from https://docs.travis-ci.com/user/encryption-keys):

`For each registered repository, Travis CI generates an RSA keypair`


Then, pypi admin or maintainer roles is needed to generate a new token. @thedrow : could you assign the maintainer role to me (pypi username: JonathanHuot). Else, you can generate a Travis token by following the URL above.
Thanks!

**Comment by thedrow** [comment]
@JonathanHuot I added you as an Owner to PyPi.

**Comment by JonathanHuot** [comment]
2.0.7 has been released by adding a new pypi token
