### ISSUE TITLE
Copy and paste bugs in service_application.py

### ISSUE THREAD

**Issue by paulie4** [oauthlib/oauthlib#532]
Can you please fix [line 149](https://github.com/oauthlib/oauthlib/blob/46f79e027a3fda7b012e3d786cbb1ee945af508f/oauthlib/oauth2/rfc6749/clients/service_application.py#L149) and line 150 to use the correct `self` properties? This is what it currently has:
```
            'aud': audience or self.issuer,
            'sub': subject or self.issuer,
```

but since the constructor sets `self.audience` and `self.subject`, those are the values that should be used, like this:
```
            'aud': audience or self.audience,
            'sub': subject or self.subject,
```

**Comment by JonathanHuot** [comment]
LGTM, do you want to provide a PR please ?

**Comment by paulie4** [comment]
Done and done.

**Comment by skion** [comment]
Thanks for the PR @paulie4!
