### ISSUE TITLE
How to over-ride `default_token_type` to JWT?

### ISSUE THREAD

**Issue by prafulbagai** [oauthlib/oauthlib#534]
Is there any setting available? Was not able to find one while going through the code.

**Comment by JonathanHuot** [comment]
Hi @prafulbagai,

**Comment by prafulbagai** [comment]
Hey @JonathanHuot - Wondering if there's any setting available?

**Comment by JonathanHuot** [comment]
We have a documentation's placeholder (https://oauthlib.readthedocs.io/en/latest/oauth2/grants/jwt.html) but even the link is not accurate/up-to-date and doesn't reflect the reality (https://github.com/oauthlib/oauthlib/issues/50 is very old and contains irregularity as pointed by @duaneking).

We can generate and use JWT with the current oauthlib version by using `token_generator` and `refresh_token_generator`. The documentation part needs an example with it.

**Comment by duaneking** [comment]
Unless this has a unit test and is documented, it literally doesn't exist for our users or the developers that are iur customers as the consumers of the API.
