### ISSUE TITLE
Community Lacks A Code of Merit

### ISSUE THREAD

**Issue by duaneking** [oauthlib/oauthlib#539]
Per the email thread where I took a PHD to task for not using the scientific method and being intellectually lazy, this community lacks a set of community contribution merit standards and as a result people who wish to contribute have no official guide on what merits their work have.

I have personally worked on projects without a merit standard , as well as ones where they explicitly list out merits. 

Based on the feedback form that email thread, I suspect that we should put more effort into ours.  I would prefer personally we simply start with http://code-of-merit.org/ as a base and edit as needed, but I wanted to open the floor to the rest of the team.

**Comment by JonathanHuot** [comment]
I never worked on projects **with** an explicit merit standard, I'm curious to know your feedback on this ? 

I've read the code-of-merit above, some of the bullets points makes sense and I think it could helps on making progress on the project, though.

**Comment by duaneking** [comment]
It really does help with egos, as well as direct efforts to what really should be the real goal of working, usable software.
