### ISSUE TITLE
Don't upload to PyPi for each environment

### ISSUE THREAD

**Issue by skion** [oauthlib/oauthlib#549]
Travis tries to upload releases for each Tox environment that is configured, leading to some errors in the [build log](https://travis-ci.org/oauthlib/oauthlib/builds/382086736). Would there be a way to do this better?

**Comment by JonathanHuot** [comment]
I think a `condition` can be made with the env. Something like below (to be tested):


    deploy:
      on:
        condition: $TOXENV = py27

**Comment by skion** [comment]
Maybe pick `py36` in that case, since it is the last one in the list and the most recent version.

**Comment by JonathanHuot** [comment]
Fixed in https://github.com/oauthlib/oauthlib/commit/6da09f284593546daac545d625f68014d7464c39

Need to wait for the next deployment to see its effect.

**Comment by JonathanHuot** [comment]
Latest 3.0.0 tagging didn't upload to PyPi at all.

After new looking at the doc, it seems they recommend to use https://docs.travis-ci.com/user/deployment/pypi/#upload-artifacts-only-once instead.

I'm updating `.travis-ci.yml` to upload pypi only once, so it should be any of the python versions depending of the first success (if all run in parallel, as expected by travis).

**Comment by JonathanHuot** [comment]
The new `.travis-ci.yml` file run the release sections for pypi & github release only for py36 tox build now. 
For all other python versions, travis stop by showing this message: `Skipping a deployment with the pypi provider because a custom condition was not met`
