### ISSUE TITLE
NotImplementedError: validate_timestamp_and_nonce

### ISSUE THREAD

**Issue by petarGitNik** [oauthlib/oauthlib#551]
Hi, I've tried implementing `validate_timestamp_and_nonce` but I received `NotImplementedError`. Looking at the [source code][1], it's obvious that the function is not implemented, but it's not really clear in the [documentation][2] whether one should subclass RequestValidator and write their own implementation. Is this by design, or is this a feature to come? 

Also, function definition accepts request object that is of type `oauthlib.common.Request`. However, given example in the documentation does not use in the function heather that object at all. Is this accidental omission?

[1]: http://oauthlib.readthedocs.io/en/latest/_modules/oauthlib/oauth1/rfc5849/request_validator.html#RequestValidator.validate_timestamp_and_nonce
[2]: http://oauthlib.readthedocs.io/en/latest/oauth1/validator.html#oauthlib.oauth1.RequestValidator.validate_timestamp_and_nonce

**Comment by petarGitNik** [comment]
I've misread the documentations, sorry, I've just seen: `OAuth providers should inherit from RequestValidator and implement the methods and properties outlined below`.  I guess, the issue can be closed now. But my second question still stands, why does an example in documentation omits request object?

**Comment by JonathanHuot** [comment]
Using `request` or not, depends of the context and the implementation. Using it in an example can be worthwile, but also can add complexity for the reader. 

Maybe a dedicated documentation's page for this object `oauthlib.common.Request` can be provided. 

That's being said, if you think updating the examples would be valuable, don't hesitate to suggest something (or create a PR to be more clear); we will be very happy !
