### ISSUE TITLE
Pass refresh token to save_bearer_token function

### ISSUE THREAD

**Issue by claweyenuk** [oauthlib/oauthlib#557]
I should preface this with I'm not sure if this is a good idea.

My desire is for the `save_bearer_token` endpoint to get passed the objects used to validate the request.  For example when refreshing a token, having access to the original refresh token.  Or when converting an authorization code to an access token, passing in the original grant.

The reason for this is that I have an endpoint that an end user can use to list all the tokens they have validated which includes when the token was first authorized.  I do this by attaching this information to some flask globals, which feels a little brittle.

**Comment by JonathanHuot** [comment]
Hi,

I'm not sure to follow, you should store the list of `access` and `refresh` tokens in a persistant store (e.g. database). You have multiple options to store every tokens you want.

**Comment by claweyenuk** [comment]
Ah, sorry, I realized my last paragraph was not that clear and I missed some important information.

So the DB has the authorized date for each token, and the reason it's there is so that a user can see all the tokens they've approved and when.

But in `save_bearer_token()` which handles writing to the DB, that info isn't readily available, so to get that info there I put that info in `flask.g` and look it up in `save_bearer_token()` just before writing.

I think it'd be nice if the auth code or refresh token info was passed to the `save_bearer_token` function somehow so that information can be persisted on these tokens even through a refresh.  That said, I do have a workaround, it's just not as explicit as I would like.

**Comment by JonathanHuot** [comment]
Have you considered putting the info in the `request` object which is passed to every `oauthlib` hooks ?

**Comment by claweyenuk** [comment]
That would be a perfect place!  Is it safe to put it in `self._params`?

**Comment by JonathanHuot** [comment]
`self._params` is a private structure used for the whole framework processing. I don't recommend using it to store custom variables. However, if you try to access to `request.refresh_token`, you should find the actual content of the `refresh_token` (list of parameters are listed in `class Request`, if available).

If you want to add custom data, you have at least two locations:
Either directly in `request`. Either in `request.client`. It will depend of the nature of your data. In the case you described, I will be more tempted to put stuff in `request.client`, this object can be a custom object, as long as you have an attribute `client_id` in it for the `oauthlib` processing.

**Comment by claweyenuk** [comment]
Great this works really well! thanks for your help!

**Comment by jvanasco** [comment]
I'm dealing with the same issue but have a different solution/request if this makes sense. I'd be willing to code a PR.

IMHO, it would make sense if the request stashed the "request_token" object as something like "request.legacy_token", which would then be cached (or read) as needed. For example, the refresh token is (often) already loaded via the `get_original_scopes` and `validate_refresh_token` functions.

In my use-case, I need to know if the original token was issued to the Application (client-credentials) or a User of the application (authorization_code).  That information is saved on the token which is being refreshed.  

I may have forked a library which is implementing things in a less-than-ideal way (flask oauthlib), but it seems that, by default, a refresh token can be queried from the database many times within a single request.
