### ISSUE TITLE
inline docs missing param?

### ISSUE THREAD

**Issue by jvanasco** [oauthlib/oauthlib#578]
https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/request_validator.py#L67-L83

shouldn't this read:

        :param client_id: Unicode client identifier
        :param request: oauthlib.common.Request

not just

        :param request: oauthlib.common.Request

?

**Comment by JonathanHuot** [comment]
Hi @jvanasco, yes it should be!
Could you open a PR with this change please ?

Thanks a lot to help improve the doc

**Comment by jvanasco** [comment]
yeah. i think this is in a few places, so I'll do a pass and make a consolidated pr.

**Comment by jvanasco** [comment]
This was addressed in #588
