### ISSUE TITLE
Fix test coverage reporting

### ISSUE THREAD

**Issue by skion** [oauthlib/oauthlib#582]
For unknown reason, coveralls appears to report an unjustified decrease in code coverage in most of our builds, such as [here](https://github.com/oauthlib/oauthlib/pull/581#pullrequestreview-150245182).

Because of this the reporting isn't useful / actionable at the moment and real problems might slip through.

**Comment by JonathanHuot** [comment]
If no solutions arises, I'd suggest to give a chance to another coverage app? That's really painful to not see the increase/decrease for each PR.

**Comment by JonathanHuot** [comment]
Three changes were required to fix this issue:
- Added `COVERALLS_PARALLEL=true` and webhook https://github.com/oauthlib/oauthlib/commit/b02809db83ad490f6ff3f1b86037272bebb4e041#diff-354f30a63fb0907d4ad57269548329e3
- Removed notifications conditions: https://github.com/oauthlib/oauthlib/commit/8ef421b85b17b6cfb651ea4f13258be0c53ed879#diff-354f30a63fb0907d4ad57269548329e3
- Added `COVERALLS_REPO_TOKEN` into list of Travis environment variables. (Value can be found in coveralls.io project's page)
