### ISSUE TITLE
Master has diverged from 2.x

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#591]
For some reasons, different documentation commits have been integrated to 2.x but are not included in master. As a result, the documentation generated at RTD (https://oauthlib.readthedocs.io/en/latest/) is missing commits. Most obvious example is the mention to Google+ community which has been dropped in favor of Gitter.

Before publishing 3.0.0, we have to fix that and make an up-to-date documentation.

**Comment by JonathanHuot** [comment]
Identified commit not merged : https://github.com/oauthlib/oauthlib/commit/f3ae98cef91e140b10d25fbd496622d879cc0c0c, but we should be sure everything is in sync.

**Comment by skion** [comment]
Should be fixed now...

**Comment by JonathanHuot** [comment]
Thanks @skion , I was thinking more than this single commit was missing, but it looks that was enough. Thanks!
