### ISSUE TITLE
Add support for Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by skion** [oauthlib/oauthlib#601]
Supporting [PKCE](https://tools.ietf.org/html/rfc7636) would help improve security for native (public) clients...

> OAuth 2.0 public clients utilizing the Authorization Code Grant are
> susceptible to the authorization code interception attack.  This
> specification describes the attack as well as a technique to mitigate
> against the threat through the use of Proof Key for Code Exchange
> (PKCE, pronounced "pixy").

**Comment by JonathanHuot** [comment]
Initial PR at https://github.com/oauthlib/oauthlib/pull/617

**Comment by amans330** [comment]
@JonathanHuot Is oauthlib now providing client support for pkce? If yes, please let me know how can I use it or point me in the right direction.

**Comment by JonathanHuot** [comment]
Hi, oauthlib is providing PKCE for OAuth2 Provider side. The integration for OAuth2 Client still need to be done; any PRs are welcomed.

**Comment by amans330** [comment]
Hi @JonathanHuot that sounds like a good idea. I have been looking for a python library that supports pkce on the client-side for a while now. Authlib comes close but is not working properly, and lacks proper documentation as well. I can work on the client-side. Should I create a new feature request or is there an existing one?
