### ISSUE TITLE
grant_type  set to variable

### ISSUE THREAD

**Issue by mlboy** [oauthlib/oauthlib#610]
“grant_type”  set to variable, because there are some non standard cases grant_type is not “authorization_code” some times it may be named "auth_code" ..

**Comment by JonathanHuot** [comment]
Hi @mlboy, it seems a reasonnable feature.
However I'm wondering if it is not already doable.

Could you specify if you are talking about client, or server, and also an example of code and error ? 

It will be a lot more meaningful.

**Comment by mlboy** [comment]
https://github.com/oauthlib/oauthlib/pull/611

**Comment by mlboy** [comment]
such as Meitu account and some  non-standard internal  systems.

**Comment by JonathanHuot** [comment]
Fixed in https://github.com/oauthlib/oauthlib/pull/625
