### ISSUE TITLE
MSSQL Integration

### ISSUE THREAD

**Issue by muscleman** [oauthlib/oauthlib#612]
Really just curious about the MSSQL integration.

I'm currently using this and getting migration errors about int to bigint conversions?

Is there a fixed version?
is this going to be fixed?

G.

**Comment by JonathanHuot** [comment]
Hi @muscleman, I know nothing about MSSQL and your description is very cryptic. Could you add more context/details, and follow the Issue template when creating an github issue please ?

Please follow either a bug report template: https://github.com/oauthlib/oauthlib/issues/new?template=bug_report.md or a feature report template: https://github.com/oauthlib/oauthlib/issues/new?template=feature_request.md
