### ISSUE TITLE
OAuth2: Revocation with Basic auth no longer possible

### ISSUE THREAD

**Issue by raphaelm** [oauthlib/oauthlib#644]
**Describe the bug**

When using the revocation endpoint, an error code ``401`` is returned even though client authentication is valid.

**How to reproduce**

* Call ``RevocationEndpoint.create_revocation_response`` with a ``headers`` dictionary containing the client authorization.
* Notice that this parameter is ignored completely. Clearly, it is overridden instantly:

https://github.com/oauthlib/oauthlib/blob/20d116c0db616285ca48ef1591a8a79796a76f5d/oauthlib/oauth2/rfc6749/endpoints/revocation.py#L41-L67

**Expected behavior**

I expected this parameter to be respected

**Additional context**

* OAuth2
* This happened with django-oauth-toolkit after upgrading to oauthlib 3.0.0
* We're implementing a provider

**Comment by JonathanHuot** [comment]
Could you check if https://github.com/oauthlib/oauthlib/pull/645 resolved your issue ?

It seems that oauthlib was lacking of unit tests around the combination of HTTP Basic Auth and Introspect/Revoke endpoints. Those have been added, too.

**Comment by raphaelm** [comment]
Seems to fix the problem, yes.

**Comment by raphaelm** [comment]
Thank you for the fast response! :heart:

**Comment by aodag** [comment]
I got the same problem, I wanna use fixed release.

**Comment by JonathanHuot** [comment]
@raphaelm / @aodag : oauthlib 3.0.1 is now released.
