### ISSUE TITLE
Remove/Delete stale git branches

### ISSUE THREAD

**Issue by duaneking** [oauthlib/oauthlib#646]
**Describe the bug**

The repo contains a lot of stale branches that make getting started in helping this project more confusing because people either didn't delete their branch after a successful merge, or gave up when we didn't merge immediately, or stopped contributing when we pushed back citing quality issues.

In general, there are far more stale branches then there are active branches.

**How to reproduce**

Login to github.
Look at the number of branches that are stale verses the ones that are active.

**Expected behavior**

No stale non-release branches should exist in the repo.

**Additional context**

I dedicated some time to this project today and I want to be sure I was looking at the correct branch as features I noticed should be included seem to be missing. This made me wonder how many branches we had, and then I looked and started to cry when I was forced to come to terms with the large number of inactive branches. ;)

- Are you using OAuth1, OAuth2 or OIDC?
N/A

- Are you writing client or server side code?
N/A

- If client, what provider are you connecting to?
N/A

- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...?
N/A

**Comment by duaneking** [comment]
Sounds good, Lets give people notice/warning but enforce it later after we give them time.  It might be worth just tagging them in this defect so they get a notice from GitHub, as well.

**Comment by JonathanHuot** [comment]
Last call for @ib-lundgren and @dgouldin, we'll delete the above stale branches in 1 week.

**Comment by JonathanHuot** [comment]
Staled branches have been deleted.
