### ISSUE TITLE
The use of unicode_literals in not supported by urllib

### ISSUE THREAD

**Issue by benjaatspencer** [oauthlib/oauthlib#661]
**Describe the bug**

Due to the use of from __future__ import unicode_literals every header dictionary manipulating function (such as oauthlib/oauth2/rfc6749/tokens.py:prepare_bearer_headers) are updating a dictionary with an key and value having the 'unicode' type. However, the use of 'unicode' data is not supported by urllib3 and it does not interact properly with (Py)OpenSSL, and thus it breaks  any application using HTTPS on python2 with moderately large payload.

See https://github.com/urllib3/urllib3/issues/855#issuecomment-216958016

This bug can be triggered using the azure python sdk to deploy a 92K json template.

Example of other bugs caused by introducing unicode data in urllib3:
https://github.com/kennethreitz/requests/issues/2914
https://github.com/urllib3/urllib3/pull/719
https://github.com/elastic/elasticsearch-py/issues/620

**How to reproduce**

1. Instrument urllib to dump the content and type of the header dictionary used to perform HTTP request.
2. Use a HTTP library making use of  oauthlib to add an Authorization bearer token, such as the msrestazure library to (e.g. using any ansible azure_rm module) and perform a REST call.
3. The instrumentation shows that all the header k-v pairs are of type 'str' _except_ the 'Authorization' key and value which are of the 'unicode' type.

**Expected behavior**

The instrumentation shows that all the header k-v pairs are of type 'str'.

**Additional context**

- Using OAuth2
- Using the downstream msrest & msrestazure libraries.
- As per HTTP RFC, request header are ASCII-encoded. See https://tools.ietf.org/html/rfc2616#section-2.2

**Suggestion**

Either:

1. OAuthlib could assume that all the headers are ASCII encoded string and the consumer of the library is not expected to run encoding function on values manipulated by oauthlib header functions. Oauthlib set header using str encoded as ASCII.

2. Document that consumer of the oauthlib header function should reencode the 'Authorization' header to the expected encoding.

3. Try to detect the type of the other headers and react accordingly (which breaks when the header dictionary is empty).

Of those, the 1. seems to me to be the most reasonable thing to do.

Thanks!

**Comment by JonathanHuot** [comment]
Hi @benjaatspencer, thanks for the report !

It seems important and it will be very nice to have a PR for that, including `1.`
