### ISSUE TITLE
Valuerror unnecessarily being thrown in production

### ISSUE THREAD

**Issue by andrroy** [oauthlib/oauthlib#662]
**Describe the bug**

We have a problem in production where user types in "illegal" character sequences, which gets sent as part of a query to our server. The problem we are experiencing is that `oauthlib` throws a `ValueError` because these character sequences are not regarded as valid hex patterns (ref https://github.com/oauthlib/oauthlib/blob/master/oauthlib/common.py#L45) 

**How to reproduce**

This can be reproduced by running `verify_request()` on a request with a string with an invalid hex patterns, e.g. this one sent by an actual user in our system:
`query=%20%C3%84%C3%B6ytqZJJ%20%%F0%9F%8F%93%F0%9F%8E%B1%F0%9F%8F%B9%F0%9F%A5%85%F0%9F%A5%85%F0%9F%A5%85%F0%9F%A4%BC%E2%80%8D%E2%99%82%EF%B8%8F%F0%9F%8F%B9%F0%9F%A5%85%F0%9F%8E%BE%F0%9F%A5%8Ao`

**Expected behavior**

When testing this locally, I've parsed the string above with [unquote](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote):
```python
from urllib.parse import unquote
unquote('%20%C3%84%C3%B6ytqZJJ%20%%F0%9F%8F%93%F0%9F%8E%B1%F0%9F%8F%B9%F0%9F%A5%85%F0%9F%A5%85%F0%9F%A5%85%F0%9F%A4%BC%E2%80%8D%E2%99%82%EF%B8%8F%F0%9F%8F%B9%F0%9F%A5%85%F0%9F%8E%BE%F0%9F%A5%8Ao')
> ' ÄöytqZJJ %🏓🎱🏹🥅🥅🥅🤼\u200d♂️🏹🥅🎾🥊o'
```

Expected behaviour in our use case would be that a request with this query goes through the oauthlib without any exceptions being thrown. I've tried to have a look at the history of `common.py`, but it's unclear to me why the hex regex is as it is. Does the query decoding need to be this strict? 

**Additional context**

- We use oauthlib through django-oauth-toolkit and django-rest-framework
- The requests are sent through our javascript-based frontend

**Comment by JonathanHuot** [comment]
Hi @andrroy for the report.

Below a shorter example:

OAuthlib:

```python
>>> from oauthlib.common import urldecode
>>> urldecode('%%20')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/doomsday/eds/oauthlib/oauthlib/common.py", line 141, in urldecode
    raise ValueError('Invalid hex encoding in query string.')
ValueError: Invalid hex encoding in query string.
```
Urllib:
```python
>>> from urllib.parse import unquote
>>> unquote('%%20')
'% '
>>>
```

Any PR are welcomed !
