### ISSUE TITLE
Question on support for Elliptical Curve Algorithms

### ISSUE THREAD

**Issue by jiyer2016** [oauthlib/oauthlib#664]
This is a question (and NOT an issue)
I use a python app called jupyterhub that inturn relies on oauthlib.

A few months back I configured a Jupyterhub installation to talk to my firm's in-house OAUTH2 Service provider. Its all working perfectly well.

A few days back, I was told that the in-house OAUTH2 Service provider is undergoing an upgrade and future versions will require integrating platforms / apps to support "Elliptic Curve algorithms".

Now, I don't understand what "Elliptic Curve Algorthims" exactly means - but I want to know if oauthlib supports it. I checked the documentation for support but could NOT make out.

Would anyone be able to advise whether or NOT support for "Elliptic Curve Algorithms" is available on oauthlib ?

Thanks in advance.

**Comment by thedrow** [comment]
Ummm what?
[Elliptic Curve Cryptography (ECC)](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) is a form of public key cryptography. That's about what you need to know.
It can be used for authenticating SSH sessions for example.

Are they talking about encrypting the token? Using ECC to authenticate that the token is valid?
It's not very clear what they are saying.

**Comment by thedrow** [comment]
Since there was no response, I'm closing this issue.
