### ISSUE TITLE
Community - Missing logo

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#684]
Hi @oauthlib, I think each project deserves its own logo and oauthlib is missing one.

I was thinking about reusing the OAuth black logo with a Python in it, or something similar.
Or, since I have no design skills, only put the two logos on the same image.

Thoughs?

**Comment by thedrow** [comment]
If you're willing to put 5 dollars on it you'll get a decent logo on fiverr or upwork.

**Comment by JonathanHuot** [comment]
my first attempt:

![oauthlib-icon](https://user-images.githubusercontent.com/820496/61945988-b3a45e80-afa1-11e9-9392-d639e0b49844.png)
![oauthlib-small](https://user-images.githubusercontent.com/820496/61945989-b3a45e80-afa1-11e9-9433-c4bff6473b4c.png)
![oauthlib](https://user-images.githubusercontent.com/820496/61945909-75a73a80-afa1-11e9-99e7-8615ab74fec6.png)


thoughts?

**Comment by thedrow** [comment]
Looks great.

**Comment by JonathanHuot** [comment]
I removed the grid behind the python logo, it looks better for medium/large size!

![oauthlib](https://user-images.githubusercontent.com/820496/62055095-36841e00-b21b-11e9-91ab-7a64f9e5c0bb.png)

**Comment by JonathanHuot** [comment]
Another design for 64x64 icons:

![oauthlib-icon-64](https://user-images.githubusercontent.com/820496/62058781-418e7c80-b222-11e9-81fc-c773954c36c4.png)

Another serie of designs for 32x32 icons:

![oauthlib-icon-32-python](https://user-images.githubusercontent.com/820496/62060421-6506f680-b225-11e9-8132-7e307def45c2.png)
![oauthlib-icon-32](https://user-images.githubusercontent.com/820496/62060422-659f8d00-b225-11e9-968c-36b98a7d018a.png)
![oauthlib-icon-32-python2](https://user-images.githubusercontent.com/820496/62060726-f1191e00-b225-11e9-915a-ce15e664ddec.png)

Any preferences?

**Comment by thedrow** [comment]
I think we can close this issue.
Feel free to reopen if I'm wrong.
