### ISSUE TITLE
Docs for validate_code require request.state to be set, but where is it used?

### ISSUE THREAD

**Issue by bertjwregeer** [oauthlib/oauthlib#687]
In the docstring for `validate_code` here: https://oauthlib.readthedocs.io/en/v3.0.1/oauth2/validator.html#oauthlib.oauth2.RequestValidator.validate_code 

It is also referenced in `save_authorization_code`: https://oauthlib.readthedocs.io/en/v3.0.1/oauth2/validator.html#oauthlib.oauth2.RequestValidator.save_authorization_code

If we have stored the `state` with the `authorization_code` we are supposed to set it on `request`, however I can't figure out why it is required. The client that is making the request to the token endpoint isn't sending the `state` at all (and I can't find where in the spec they are required to either)

Isn't the point of the `state` supposed to be a way for the remote service that is doing the Oauth2 dance to verify the user they sent to the provider is the one that is returning and that it's not someone else attempting to have a user log in when the user didn't request that?

**Comment by JonathanHuot** [comment]
Hi @bertjwregeer, thanks for the report, you are entirely right.

We already removed these references in the master branch. You can check the latest documentation at:

https://oauthlib.readthedocs.io/en/latest/oauth2/validator.html#oauthlib.oauth2.RequestValidator.validate_code
https://oauthlib.readthedocs.io/en/latest/oauth2/validator.html#oauthlib.oauth2.RequestValidator.save_authorization_code

We're going to mark the documentation as "3.0.2" release as well, it should be available soon.

**Comment by bertjwregeer** [comment]
Thanks @JonathanHuot!
