### ISSUE TITLE
OAuth1: can't verify SHA256 signature in server with OAuth1

### ISSUE THREAD

**Issue by hmoffatt** [oauthlib/oauthlib#690]
In my server code I am receiving OAuth1 requests signed with SHA1 and 256. oauth1 requests signed with HMAC-SHA1 work, but HMAC-SHA256 signatures fail to validate.

I see that the code in oauthlib/oauthlib/blob/master/oauthlib/oauth1/rfc5849/endpoints/base.py tests for SIGNATURE_HMAC (SHA1), else it assumes it is plaintext. There is no handling of SHA256.

I am using lti (https://github.com/pylti/lti) which uses oauthlib and requests-oauthlib. I am able to sign with SHA256 correctly in my test client, and the resulting signatures fail at the server. As I am not using oauthlib directly I can't give you a simple test case.

**Comment by JonathanHuot** [comment]
If you have the current sample with lti and its behavior (output, exception, ..) that's maybe a start, even if not ideal I agree.

Thanks for the report & the PR !

**Comment by hmoffatt** [comment]
pylti is calling SignatureOnlyEndpoint.validate_request() here:
https://github.com/pylti/lti/blob/master/src/lti/tool_provider.py#L54

Without this fix I was getting the following logged:

```
INFO: [Failure] request verification failed. [in signature_only.py:81]
INFO: Valid client: True [in signature_only.py:82]
INFO: Valid signature: False [in signature_only.py:83]
```

With the modified code validation is passing.
