### ISSUE TITLE
Add redirect_uri to authorization_code model in `docs/oauth2/server.rst`

### ISSUE THREAD

**Issue by pietdaniel** [oauthlib/oauthlib#712]
**Describe the feature**

The [authorization_code model description here](https://github.com/oauthlib/oauthlib/blob/master/docs/oauth2/server.rst#authorization-code) does not include a `redirect_uri` field. In [oauthlib/oauth2/rfc6749/request_validator.py](https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/request_validator.py#L103-L107) it states that the `redirect_uri` should be compared against the `authorization_code` and not the `client`.

To support this, the `authorization_code` model description in the [docs](https://github.com/oauthlib/oauthlib/blob/master/docs/oauth2/server.rst) should include the `redirect_uri` used.

**Additional context**

This issue is relevant to the OAuth2 "Creating a Provider" Docs.

**Comment by pietdaniel** [comment]
I have a fork with a potential fix: https://github.com/pietdaniel/oauthlib/commit/00d4d5a62d4bf18fd2642cd667f7e2002211668c

**Comment by JonathanHuot** [comment]
Hi @pietdaniel, it was missing, thanks for adding it !

After reviewing this, I noticed that the `nonce` (for OIDC) is also missing but we never went to the whole OIDC model in the docs anyway. I have created https://github.com/oauthlib/oauthlib/issues/713 to follow-up on this.

**Comment by JonathanHuot** [comment]
The changes you did on the docs LGTM. Please feel free to open a PR.

**Comment by pietdaniel** [comment]
PR: https://github.com/oauthlib/oauthlib/pull/714
