### ISSUE TITLE
Release 3.1.1

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#736]
Based on latest contributions and the previous release was not so recent, I suggest to release 3.1.1.

That will be a good opportunity for @auvipy to make your first release, if you want ;)

BTW: to synchronize that will be helpful if you join the oauthlib gitter community.

**Comment by auvipy** [comment]
what is the link? I would love to contribute

**Comment by auvipy** [comment]
i joined!

**Comment by JonathanHuot** [comment]
I tried to add milestone "3.1.1" to closed issues and PR. Then, it could be useful to create a PR with Changelog description, and maybe we could discuss based on that.

Once everything are in master, tagging the new version should trigger the build process to release a github version and pypi. I think we should probably document the release process as well.

**Comment by auvipy** [comment]
that sounds reasonable to me

**Comment by auvipy** [comment]
hey, may I get your email? or you could shot me auvipy@gmail.com

**Comment by mvaled** [comment]
What's the status of this release?

**Comment by JonathanHuot** [comment]
@mvaled : it is ready, only some paperwork are still needed to deploy it.
@auvipy : do you have time to finish it for this year?

**Comment by auvipy** [comment]
I can, but do I need PyPI access for that?

**Comment by JonathanHuot** [comment]
The release rollout must be done by creating a PR with all changelog and version changes. Once it is reviewed and merged, we can tag the git revision and tagging will automatically release a pypi release with Travis.

**Comment by auvipy** [comment]
> The release rollout must be done by creating a PR with all changelog and version changes. Once it is reviewed and merged, we can tag the git revision and tagging will automatically release a pypi release with Travis.

oh OK

**Comment by valentijnscholten** [comment]
I think this is really needed because with the newer pips installing requirements may break due to the dependency on an old PyJWT version: https://github.com/oauthlib/oauthlib/commit/b69fa53fd836dc559aa7fcd78ce075bcbe361629

**Comment by Sri-krishna98** [comment]
Yes oauthlib 3.1.0 is already causing CVE issues checkout PRISMA-2021-0041, the CVE scan setup in our pipeline throws a high severity vulnerability for this package, can you please update it as it's been quite some time

**Comment by rolweber** [comment]
Hmm, this issue was created a year ago, and still no new release. Things seem to have stalled a bit.

That [CVE 2021-0041](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-0041) is currently reserved, but not yet disclosed. Maybe a fix is in the making.

**Comment by JonathanHuot** [comment]
Give me a couple of days and I will trigger the release. Thanks for your patience

**Comment by Sri-krishna98** [comment]
Thanks for looking into this👍

**Comment by JonathanHuot** [comment]
Release is finally out. Sorry for the delay, and enjoy...
3.2.0 coming soon with remaining PRs

**Comment by ankit-jha** [comment]
> Release is finally out. Sorry for the delay, and enjoy... 3.2.0 coming soon with remaining PRs

Please start the new year with the new release.
We're waiting on it.
