### ISSUE TITLE
with slack, validate_token_parameters fails with MissingTokenError

### ISSUE THREAD

**Issue by abe-winter** [oauthlib/oauthlib#740]
**Describe the bug**

When using slack as a provider, the `parse_token_response` method fails with `MissingTokenError` (inside `validate_token_response`).

**How to reproduce**

From requests-oauthlib, something like:

```
sesh = OAuth2Session(CLIENT_ID, state=flask.session['oauth_state'])
token = sesh.fetch_token(TOKEN_URL, client_secret=CLIENT_SECRET, authorization_response=flask.request.url)
```

**Expected behavior**

Not sure; I'm guessing slack's reply format is non-standard.

Slack's reply format [documented here](https://api.slack.com/authentication/oauth-v2#exchanging) has `access_token` keys at the top level and under `authed_user`. I think these docs are wrong: in the pure sign-in case (with no 'bot permissions' requested), slack doesn't have a top-level `access_key` field in this response, hence the error.

Ideally there would be a flag or environment variable to skip the `validate_token_response` call in `parse_token_response`. (Similar to how `OAUTHLIB_STRICT_TOKEN_TYPE` env is used).

I'm willing to submit a PR if useful; let me know.

**Additional context**

Please provide any further context here.

- Are you using OAuth1, OAuth2 or OIDC? **oauth2**
- Are you writing client or server side code? **client-side, i.e. my web server is connecting to an oauth provider**
- If client, what provider are you connecting to? **slack**
- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...? **requests-oauthlib**

**Comment by thedrow** [comment]
I don't think we should support any non-standard use case.
Is it not possible to override `validate_token_parameters` and adjust it to your usecase?

**Comment by abe-winter** [comment]
you mean override using configuration? or like monkeypatch

**Comment by thedrow** [comment]
I mean inheriting from the relevant class and constructing a client from it.
The current design allows it.

There's no need for monkeypatching.

**Comment by abe-winter** [comment]
neat, thank you.

that works for my use case.

closing this, thanks + sorry to bother.
