### ISSUE TITLE
How to integrate as an idP with AWS cognito?

### ISSUE THREAD

**Issue by adnanmuttaleb** [oauthlib/oauthlib#742]
The [guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html#manage-oidc-provider-console) for adding OIDC provider in aws cognito says that you should add a **Thumbprint** for your idP. Is the Thumbprint equivalent  to the public-key, used to verify the issuer of the id tokens? how to get it? 

The guide mention  `/.well-known/openid-configuration` endpoint and `jwks_uri` in order to construct this Thumbprint, but I could not find anything about this endpoint in the docs. Any help is appreciated :) .

**Comment by r4fek** [comment]
@adnanmuttaleb did you manage to solve this issue?

**Comment by adnanmuttaleb** [comment]
@r4fek [this](https://stackoverflow.com/questions/64895604/how-aws-cognito-verify-the-identity-token-issued-by-my-own-idp/64952181#64952181) may help you, I added a question and answer.
