### ISSUE TITLE
OIDC request_type "code token" does not save access token

### ISSUE THREAD

**Issue by kazkansouh** [oauthlib/oauthlib#755]
I was experimenting with `django-oauth-toolkit` and noticed when setting a request type of `code token` the returned access token was not valid because it was not saved into the database. Looking into the issue I believe that during the hybrid flow for `code`, after the token is generated there is a missing call to `request_validator.save_token(code, request)`.

That is, the following code:

https://github.com/oauthlib/oauthlib/blob/d54965b86ce4ede956db70baff0b3d5e9182a007/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py#L272-L279

After `oauth2.rfc6749.grant_types.base.GrantTypeBase.add_token` is called as a modifier there is no corresponding call to `request_validator.save_token`. That is, I would have expected (based on examining the implicit flow) to see something like the following present:

```python
if 'access_token' in grant:
  self.request_validator.save_token(grant, request)
```

Alternatively, if `save_authorization_code` is expected to make this check then this is an issue for the `django-oauth-toolkit` project.

### Version

```plaintext
$ pip3 freeze | grep oauth
django-oauth-toolkit==1.5.0
oauthlib==3.1.0
```

**Comment by JonathanHuot** [comment]
Hi, it seems a mistake for hybrid mode; I suppose a problem of oauthlib itself. Does anyone has some time to have a look on it for a PR ?

**Comment by kazkansouh** [comment]
I'd be happy to submit a PR that implements the solution I outlined above - assuming it is good?

**Comment by JonathanHuot** [comment]
That would be very kind, yes.
