### ISSUE TITLE
the library Do you support AUTOAPPROVE

### ISSUE THREAD

**Issue by jinji-hanbin** [oauthlib/oauthlib#758]
Spring OAuth2 support autoapprove，Skip the user authorization page

**Comment by jinji-hanbin** [comment]
@thedrow

**Comment by thedrow** [comment]
This library does not support auto approval as far as I know.

**Comment by jinji-hanbin** [comment]
@nsklikas

**Comment by jinji-hanbin** [comment]
@auvipy @nsklikas

**Comment by nsklikas** [comment]
I'm not sure what you are referring to. Do you mean `prompt=none` in the OIDC flow?

afaik it is up to the implementation (the library calling oauthlib) to decide whether the user will be requested to authenticate.

**Comment by nsklikas** [comment]
What I don't understand about your questions is: oauthlib offers you a server and some hooks, how you choose to authenticate the user is up to your implementation and the frontend that you choose to use.
