### ISSUE TITLE
travis-ci.org is shutting down May 31, 2021. Switch to GHA?

### ISSUE THREAD

**Issue by n2ygk** [oauthlib/oauthlib#762]
**Describe the feature**

travis-ci.org is [shutting down](https://blog.travis-ci.com/2021-05-07-orgshutdown) at the end of May 2021 (in 2 days!):

Many OSS projects have converted to using GitHub Actions. Consider doing the same or convert to using travis-ci.com

**Comment by n2ygk** [comment]
@JonathanHuot ^

**Comment by JonathanHuot** [comment]
Thanks for the heads-up; it seems travis-ci.org is only "migrated" to travis-ci.com without major changes; so I think the less effort should be to move the hooks and try... I am currently releasing 3.1.1 with travis-ci.org, and then, we can switch to travis-ci.com for 3.2.0.

I never used GitHub Actions, so I'm not sure to get the benefits... but feel free to expose your view if you want.

**Comment by JonathanHuot** [comment]
Migration has been done, and I played around GH Actions with requests-oauthlib. 
I have not yet any strong preference between TravisCOM and GH, so I will not encourage doing a migration, unless we have a real benefit.
