### ISSUE TITLE
Requests-Oauthlib appears to be unmaintained

### ISSUE THREAD

**Issue by satiowadahc** [oauthlib/oauthlib#768]
**Describe the bug**

There has been no accepted changed in the last few years, missing some updates that are sitting in PR's

**How to reproduce**

Start an FOSS project

**Expected behavior**

Community Maintains projects.

**Additional context**

Jokes of the boilerplate aside. It seems this is a relatively small library and closely related to Oauthlib. Is there any thought of
adding the relevant additions to this library?

- Are you using OAuth1, OAuth2 or OIDC?
Oauth2 fwiw
- Are you writing client or server side code? 
Client
- If client, what provider are you connecting to? 
Autodesk
- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...? 
requests-oauthlib

**Comment by thedrow** [comment]
If you'd like to fork and have us transfer ownership of the fork to this organization, I think that might work.

**Comment by JonathanHuot** [comment]
hi @satiowadahc, we have fixed the requests-oauthlib pipeline and are working on reviewing issues and merging PR and publishing new releases (v1.3.1 is out, working on 1.4).

Please feel free to continue working on it.
