### ISSUE TITLE
Hook to revoke refresh token after use

### ISSUE THREAD

**Issue by jw-00000** [oauthlib/oauthlib#770]
I'm using oauthlib to implement an OAuth 2.0 provider. When a refresh token is used, i.e. a request is made to `/token` with `grant_type=refresh_token&refresh_token=123`, the OAuth spec states "The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client." ([section 6](https://datatracker.ietf.org/doc/html/rfc6749#section-6), last paragraph). However, I don't see how to easily implement this using oauthlib.

oauthlib first calls my validator's `validate_refresh_token` and if this succeeds it calls `save_bearer_token` with a new access token and refresh token. I could revoke the old refresh token in `validate_refresh_token`, after validating the old one, but that doesn't really seem like the right place. In `save_bearer_token`, I no longer have access to the old refresh token so I can no longer look it up in my database to invalidate it (+ this function is also used by other grant types).

Maybe a new method should be added to the request validator to support this?

**Comment by JonathanHuot** [comment]
Hi @jw-00000 , have you checked if you can put it in `rotate_refresh_token` ? See the flow https://oauthlib.readthedocs.io/en/latest/oauth2/server.html
