### ISSUE TITLE
PRISMA-2021-0041 - There is no support for PKCE implementation in the oauthlib client

### ISSUE THREAD

**Issue by bobpach** [oauthlib/oauthlib#774]
PRISMA-2021-0041 - There is no support for PKCE implementation in the oauthlib client. Client-side PKCE for OAuth2 RFC 7636 is required for applications to have secure communication with the authorization server. OAuth 2.0 public clients utilizing the Authorization Code Grant are susceptible to the authorization code interception attack.**Describe the bug*

**Comment by jjlangen** [comment]
I also have this issue. It seems there is an (in)active PR on this issue #743

**Comment by thedrow** [comment]
Feel free to take over. All contributions are welcome 😄

**Comment by gandhirajan** [comment]
@auvipy I saw that the PR related to this issue is merged. Could please provide some info on when is the planned release for this fix?

**Comment by auvipy** [comment]
we can expect very soon, we just need a license issue fixed and update some release notes

**Comment by gandhirajan** [comment]
@auvipy Thanks for the instant update.

**Comment by auvipy** [comment]
closing in favor of https://github.com/oauthlib/oauthlib/pull/786
