### ISSUE TITLE
create_userinfo_response ignores Access Token's granted scopes.

### ISSUE THREAD

**Issue by n2ygk** [oauthlib/oauthlib#799]
**Describe the bug**

`create_userinfo_response()` ignores the Access Token's granted scopes which prevents properly [Requesting Claims using Scope Values per the OIDC core spec section 5.4](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

**How to reproduce**

See this [example code snippet for a django-oauth-toolkit OP](https://github.com/n2ygk/dot-tutorial/blob/ffb594224f0d5de3e4ddc6cd97f0f54683b360ca/my_oidc/oauth_validator.py#L25-L59).

**Expected behavior**

I would expect that `request.scopes` contains the scopes granted to the access token in the `Authorization: Bearer` header. However, the scopes list contains only `openid`.

**Additional context**

This code explicitly sets the scopes to `["openid"]` only:

https://github.com/oauthlib/oauthlib/blob/cc5216eb10f2bee34662471c90ba623ce0620bd9/oauthlib/openid/connect/core/endpoints/userinfo.py#L29-L41

- Are you using OAuth1, OAuth2 or OIDC? OIDC
- Are you writing client or server side code? server
- If client, what provider are you connecting to?
- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...? django-oauth-toolkit

**Comment by auvipy** [comment]
Based on what you describe I would say if you could come with a proposed solution/PR that would be mostly welcome.

**Comment by n2ygk** [comment]
I'm not sure I understand the logic in oauthlib sufficiently to do this. I would want someone with a strong understanding of the reason request.scopes is hardcoded to "openid". Perhaps @JonathanHuot can answer that.

However It looks like this can be worked around in DOT by explicitly passing the `access_token` to `get_oidc_claims`, and then the scopes are available from the `access_token`.

**Comment by JonathanHuot** [comment]
Hi @n2ygk, 

After reviewing the code, I think the line https://github.com/oauthlib/oauthlib/blob/master/oauthlib/openid/connect/core/endpoints/userinfo.py#L39 with `openid` hard-coded is just ignored and can be removed with no effects.
Note that the `RequestValidator.validate_bearer_token` is called just after and must set the `request.scopes` based on the Bearer Access Token permissions. So it should override the hard-coded value set before.

Once set, the `get_userinfo_claims` implementation should read the `request.scopes` and other things related to claims, and return the claims and that should be it.

More generally, I think it is missing in oauthlib a way to map scopes with claims (i.e. `email` scope should give `email` and `email_verified` claims). Any PRs in this direction are more than welcome!

**Comment by n2ygk** [comment]
@JonathanHuot Aha! I see on further reading of downstream DOT's [validate_bearer_token](https://github.com/jazzband/django-oauth-toolkit/blob/f46439e69844feb12fc8e5a6dcb99dd569abec3f/oauth2_provider/oauth2_validators.py#L397-L404
) that it is confusing the _minimum list of scopes required_ to access the userinfo endpoint ("openid") with the scopes granted in the access token:
```
    def validate_bearer_token(self, token, scopes, request):
        ...
        if access_token and access_token.is_valid(scopes):
            request.client = access_token.application
            request.user = access_token.user
            request.scopes = scopes  # <--- this should be access_token.scopes


            # this is needed by django rest framework
            request.access_token = access_token
            return True
```

**Comment by JonathanHuot** [comment]
Oh yes! good catch :) 
So the `openid` is required as it is a needed scope to access the userinfo endpoint... That's hard to understand as we're mixing and reusing functions here, but now it is clear :)

**Comment by n2ygk** [comment]
> Oh yes! good catch :) So the `openid` is required as it is a needed scope to access the userinfo endpoint... That's hard to understand as we're mixing and reusing functions here, but now it is clear :)

Hopefully I got it right. The uses of variable names like `scopes` seems to sometimes refer to required scopes and otherwise requested or granted scopes.

I think we can move along and close this issue;-)  I'll think more about your suggestion and whether I can move my [implementation](https://github.com/jazzband/django-oauth-toolkit/pull/1108) up from DOT:

>  More generally, I think it is missing in oauthlib a way to map scopes with claims (i.e. email scope should give email and 
 > email_verified claims). Any PRs in this direction are more than welcome!

Scope-based claims is easy. Responding to a claims request is perhaps too complicated to bother implementing. I'm not aware of any clients that implement that feature.
