### ISSUE TITLE
CI/Pipeline broken since TravisCI consumed all "OSS credits"

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#833]
Because we're running a OSS project, we have a 10000 credits in Travis-CI.com to run jobs. The pipeline stopped working around June, I thought initially it should be enough (https://github.com/oauthlib/oauthlib/issues/762) but apparently it is only enough for a couple of months of usage!

I have sent an email to Travis support to see if we can have more credits dedicated to oauthlib, else we may need to switch to Github Actions before processing more pull requests.

Thoughts anyone?

**Comment by auvipy** [comment]
I was talking about GHA move lately

**Comment by JonathanHuot** [comment]
Closed in https://github.com/oauthlib/oauthlib/pull/834
