### ISSUE TITLE
Latest version on pypi.org (3.2.2) not reflected here - is it safe?

### ISSUE THREAD

**Issue by nizwiz** [oauthlib/oauthlib#842]
The latest version on pypi.org appears to be 3.2.2, but that version appears neither in the [Changelog](https://github.com/oauthlib/oauthlib/blob/master/CHANGELOG.rst) nor in the [releases](https://github.com/oauthlib/oauthlib/releases) here on github. What changes does 3.2.2 on pypi contain?

**Comment by JonathanHuot** [comment]
Hi @nizwiz , thanks for reporting, we have added a Github release and added info to the Changelog.
